name: ISS Tracker

on:
  schedule:
    - cron: "*/4 * * * *"  # joka 4. minuutti
  workflow_dispatch:       # manuaalinen ajo GitHubista

jobs:
  run-iss-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ISS script
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_RECEIVER_NRO: ${{ secrets.TWILIO_RECEIVER_NRO }}
          TWILIO_FROM_NRO: ${{ secrets.TWILIO_FROM_NRO }}
        run: python main.py
